### ISSUE TITLE
SDL 2 port

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#169]
Seems like a big task, need to investigate: http://wiki.libsdl.org/MigrationGuide

Why port?
- SDL 2.x has gone stable
- SDL 1.2.x will gradually see worse support
- There are some features we may benefit from:
  - Multiple windows/displays - maybe one day we can have 8 or 16 split screen local multiplayer! :laughing: 
  - Android/iOS support - we already have an Android port so it's not a big issue, but iOS is a big one. **SDL 2.x is under zlib license so iOS ports will be legal** :smiling_imp: 
  - Better fullscreen support - not sure what that entails, but sounds nice
  - Basic Drag'n'Drop support - can use in the classic editor for opening .cpn files by dragging them into the window
  - Support joysticks being plugged in/out - always nice

And now the bad news:
- No/poor/unknown support for Haiku, BSD etc. No more toaster ports :frowning:

**Comment by cxong** [comment]
Yet another reason for SDL2: we can use this: https://github.com/gabomdq/SDL_GameControllerDB with the function `SDL_GameControllerAddMappingsFromFile` which will give good button names for controllers.

**Comment by sauer2** [comment]
@cxong :+1: 

Also, SDL2 seems pretty stable now, unlike in 2013.

**Comment by carstene1ns** [comment]
Well, an actual port with the current features is possible by using the current rendering (doing pixel manipulation, blit to screen) as SDL2 supports it (to be backward compatible). However, as already mentioned, to make use of all the new features (hardware accelerated textures and such) a major re-factoring would be necessary. I would like to keep compatibility for SDL1.2 until that re-factoring happens.
With a bit of cmake-magic and some `#ifdef' stuff, this should be do-able in a day or two.
