### ISSUE TITLE
Cyberdogs weapons

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#268]
Split from #71 
Should be easy once the weapon/bullet refactors are complete #64 
##

**Comment by sauer2** [comment]
@cxong Isn't this ticked done?

**Comment by cxong** [comment]
yes and no; the pistol and launcher guns are inspired by cyberdogs guns but they're not perfect replicas, and to recreate cyberdogs then all the guns should be the same. Obviously with the custom weapon feature then this is easy to do, so now this issue is more like a todo entry for #71

**Comment by cxong** [comment]
https://github.com/cxong/cyberdogs/blob/main/globals.pas#L180

- powergun (range 70 rate 40 power 60 speed 10 radius 5)
- blaster (range 50 rate 12 power 10 speed 8 radius 4)
- MiniGun (range 30 rate 7 power 6 speed 12 radius 3)
- Flamer (range 25 rate 7 power 10 speed 3 radius 10)
- Launcher (range 50 rate 30 power 40 speed 4 radius 1)
- DumbGun (range 110 rate 40 power 5 speed 4 radius 0)
- Gun (range 110 rate 30 power 3 speed 8 radius 0)
- Lazer (range 100 rate 65 power 10 speed 10 radius 0)
- TurboLazer (range 100 rate 35 power 8 speed 10 radius 0)
- Zapper (range 30 rate 7 power 10 speed 12 radius 6)

**Comment by cxong** [comment]
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L905
Ammo pickups

- powergun 5
- blaster 50
- minigun 100
- flamer 50
- launcher 5

note: minigun = sprayer, launcher = grenade, megagun = zapper

**Comment by cxong** [comment]
Chainsaw:

Starts of bare handed
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/equip.pas#L199
but every chainsaw increases melee damage by 2 (per tick)
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/equip.pas#L331
up to a max of 10 (5 chainsaws)
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/equip.pas#L292

Picking up a chainsaw on a map automatically sets chainsaws to max (5 chainsaws)
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L920

Enemies range from 0-3 damage per tick (equivalent to barehanded, half chainsaw, all the way up to 1.5 chainsaws)
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L372-L453
(but it appears this pickup is disabled)

**Comment by cxong** [comment]
Few notes about weapon/bullet attributes:

## Speed

In C-Dogs, player speed is 256, whereas in Cyberdogs it's 8
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/dogs.pas#L403
Also, bullet speed is multiplied by the muzzle factor, which is 3. So to get a C-Dogs equivalent speed, we need to multiply by (256 / 8 * 3) or 96. So when a bullet has "10" speed, its speed equivalent in C-Dogs is 10 * 96 = 960

## Range

Number of ticks the bullet lasts for, same as C-Dogs

## Rate

Cooldown ticks per shot, same as "Lock" in C-Dogs
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L820

**Comment by cxong** [comment]
Bullet sprites: https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/pics.pas#L135-L143

https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/screen.pas#L216

(bulletStyle, bullet sprites, hit spark)

- Blaster: 0, short cyan beam, cyan ball
- Dumbgun: 1,  red beam, red ball
- Minigun: 2, small yellow ball, yellow ball
- Flamer: 3, flames, flames
- Launcher: 4, grenade, grenade
- Gun: 5, short green beam, green ball
- Lazer/Turbolazer: 6, yellow beam, yellow ball
- Powergun: 7, blue orb, blue ball
- Zapper: 8, alternating red/yellow ball for some reason, fireball

Note: zapper = megagun, so I think the source doesn't match the released game - megagun bullet should look the same as the launcher

**Comment by cxong** [comment]
For the launcher / megagun, when they hit something they explode, creating randomly dispersed fireballs, but the fireballs are ornamental only. The real damage they do is to every target within a radius-100 square:
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L607-L625

**Comment by cxong** [comment]
Note that the megagun isn't implemented fully in the source code, because it's an older source. From playtesting, the megagun kills everything in one shot except for the destroy objectives which take 2.
https://youtu.be/0ORsSJWOyMM?t=358

**Comment by cxong** [comment]
![guns](https://user-images.githubusercontent.com/1083215/166099176-c1a7c261-ffb7-4450-9f59-4ff2d94d4ec2.gif)
