### ISSUE TITLE
Particle Emitters

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#287]
As we add more particle effects, we're starting to need emitters as well: game entities that produce particles.

The gore effects #180 already need emitters, as right now there's a hand-crafted loop to create the blood splatter.

Emitters can enable the following fancy effects:
- Blood leaving trails as they fly
- Smoke trails for rockets
##

**Comment by sauer2** [comment]
How about static particle effects or lightening particle effects for weapons?
For example, like this: http://gamedevelopment.tutsplus.com/tutorials/how-to-generate-shockingly-good-2d-lightning-effects--gamedev-2681

**Comment by cxong** [comment]
Good idea, although there's nothing that currently requires lightning effects. Maybe once we add a lightning gun of some sort?

**Comment by sauer2** [comment]
Another possible weapon: The Cleanser, a very short range grenade that zaps near objects/foes/npc to ashes.

**Comment by sauer2** [comment]
@cxong In the unreal engine, lightening emitters are just a special case of [beam emitters](https://www.youtube.com/watch?v=ywd3lFOuMV8). That might be a wishlist feature request, but if you implement it, it might also come in handy for hitscan weapons like sniper rifles. Especially if it can fade from one side (like a jet trail) or fade partially (like at first there is the full beam, then it gets thinner or less intense, then only parts or sparks are shown).
