### ISSUE TITLE
Travis-CI Deployment? [$100]

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#290]
It may be possible to have Travis-CI automatically deploy to Github releases, according to http://docs.travis-ci.com/user/deployment/releases/

This will cut out some of the manual work involved in making releases.

**Comment by cxong** [comment]
Hey @meZee, I forgot to mention, how would you like to be credited in [`CREDITS`](https://github.com/cxong/cdogs-sdl/blob/master/doc/CREDITS)? Is `meZee` fine or do you prefer another name?

**Comment by meZee** [comment]
meZee is perfectly fine, thank you very much.
