### ISSUE TITLE
Revamp the Wii Port

### ISSUE THREAD

**Issue by carstene1ns** [cxong/cdogs-sdl#296]
Things that need to be done:
* [ ] button mapping (with sdl_wii, wiimote sends joystick events)
* [x] toolchain file
* [x] auxiliary data (meta.xml, icon.png)
* [ ] filesystem access
* [ ] polishing
* [ ] documentation

This depends on #280, because physfs does not compile on wii without modifications, but I made a [rough port some time ago][1] that can be used.

[1]: https://github.com/carstene1ns/physfs20-wii

**Comment by cxong** [comment]
Recently I removed physfs because it's not really needed, plus I suspect it was causing problems with the GCW-Zero port. Hope this helps!

**Comment by carstene1ns** [comment]
Unfortunately there is no SDL2 for Wii (yet). Closing for now.
