### ISSUE TITLE
Vehicles, turrets

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#30]
i.e. something players can get into, which changes their weapon and/or movement style. Also could add autoturrets, which just don't move.
##

**Comment by sauer2** [comment]
Turrets could be implemented like this, for maximal flexibility:

- bullets optionally can place static map objects instead of doing damage
- static map objects optionally can fire weapons, with an optional auto-aim tag and ammo limit

You could maybe even implement a half-life style health dispenser this way, if you set the bullet damage to -1.

**Comment by sauer2** [comment]
Or, if you at the same time allow bullets to be static map objecs, you could implement shooting drones.

**Comment by cxong** [comment]
This feature should probably be split as we built it out in parts. Initially we could build it on top of the custom gun system. E.g.

**MG emplacement**
- Makes you immobile (speed = 0)
- Drops when you switch away from it; doesn't stay in your inventory
- Fixed muzzle position (have a map object as its parent?)

**Turret emplacement**
In addition to the above:
- Can "enter" the turret (hide player, disable collisions)
- Destructible (map object parent is destructible; need to eject player on destruction)

**Jetpack**
- Does not change player's gun; they can fire the gun they were holding when they "entered" the vehicle
- Change player physics (more speed, inertia)
- Disable sliding (or custom action when pressing move + switch?)

**Hoverbike**
In addition to the Jetpack:
- Destructible (movable map objects?)
- Mass (can be knocked back, knocks back actors on collision)

**Motorbike**
- Basic vehicle physics: has a heading, accelerates while moving towards heading, decelerates and turns while moving to a different heading, brakes while moving opposite to the heading. Need to add the following properties:
  - heading
  - vehicle rotation (directional sprites for map objects?)
  - deceleration
  - braking
  - acceleration angle threshold
  - braking angle threshold

...

**Comment by cxong** [comment]
Went with a different design - vehicles are a special type of actor, and added two references to actors: pilot and vehicle
For the pilot, it controls the vehicle instead of itself, doesn't get drawn and doesn't react to collisions - instead it always follows the vehicle
For the vehicle, it doesn't control itself, and when drawn, will draw the pilot's head instead (if being piloted)

Having vehicles act as actors means minimal changes to other parts of the code.
