### ISSUE TITLE
Custom guns occacionally shoot in a perfectly straight line

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#320]
Hi! Sometimes, when using custom guns (see here: http://forum.freegamedev.net/viewtopic.php?f=22&t=4654#p59474), all guns shoot in a perfectly straight line instead of dispersing properly. Note that in this weapon set, all guns except pistols and sniper guns have some dispersion. This bug is most notable for shotguns and machine guns. Shotguns are an interesting case here; here all 5 bullets are shot in a straight line, but it looks like a single bullet. I know that because of the damage it causes.

I have no idea what causes this bug nor have I any idea how to reproduce it. It also happens only sporadically in a single mission. When exiting or finishing this mission, the bug may or may not be gone after the next mission has been started.

The only thing I know is that it only happens with the custom guns, but it did not happen with the default weapons so far.

I experience this bug in 9fe5d8a95ec423d8303051ab33c659ce545eabe0 and some earlier versions; I haven’t changed the gun definitions so far.
##

**Comment by sauer2** [comment]
Can confirm, I had this testing @Wuzzy2 s campaign.

**Comment by sauer2** [comment]
@Wuzzy2 
Could you test the latest development version? Or the next release, if you don't have the time for compiling the game?

I think @cxong probably fixed it, but it would be good to check this out, in case my ticket that he referenced wasn't the same after all...

**Comment by Wuzzy2** [comment]
I can't reproduce this issue in dev right now. It might be still there, I could just be “lucky” to not spot the bug this time.
