### ISSUE TITLE
game crashes when saving new character

### ISSUE THREAD

**Issue by muir1** [cxong/cdogs-sdl#352]
* compiled cdogs-sdl from cloned repo
* run **/cdogs-sdl/src/cdogs-sdl

from main menu:
`quick play` => `1` => `Save` => `(new)`

game crashes with following error:
```
cdogs-sdl: **/cdogs-sdl/src/cdogs/c_array.c:106: CArrayGet: Assertion `idx >= 0 && idx < (int)a->size' failed.
```

**Comment by cxong** [comment]
Thanks for raising!
