### ISSUE TITLE
Editor: Help screen is only shown shorly when numlock is off

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#354]
I discovered a strange bug (?) in the editor:

When I open the help screen by pressing F1, the help screen goes away after about 1 second if numlock was off. If numlock was on, the help screen stays.
I do not know which other information may be relevant to this. If you need more information, just ask. :)

Discovered in: c822590370c4ad12bf0c271cb74517440c64d14b

**Comment by cxong** [comment]
good catch; this was due to the lock keys being picked up by the key repeat code
