### ISSUE TITLE
Moving health gauge animation

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#360]
When you gain or lose an amount of health, briefly show the old and new health levels, then animate the old level away.

For example, in Diablo, when you drink a health potion, your health doesn't immediately fill; a faded-red background is added, and your real health gradually climbs up to that level.

Similarly, in Bloodborne, your new health level is indicated first, and your real health moves until it matches the indicator, which then disappears.

This gives the player a moment to see and appreciate how much health has changed.
##

**Comment by cxong** [comment]
Other ways to enhance the HUD, specifically to make the important parts visible even in [peripheral vision](http://gamasutra.com/blogs/BobTilford/20160329/268648/Perceiving_without_looking_Designing_HUDs_for_peripheral_vision.php):

- [ ] Modify brightness based on gauge level (afaik already done for the health gauge, extend to the reload gauge)
- [ ] Pulse animation when health is critical
- [ ] Use colour animation when the gauge is changing (i.e. flash the gauge to green when gaining health, gradually fading back to the normal colour, similarly flash red when losing health)

**Comment by cxong** [comment]
@flags thanks for the implementation; it's great.

One point though: the gauge animation is too brief; the gauge starts animating as soon as it changes, at 1 point per frame. C-Dogs runs at 70 fps, and since most damage in the game is about 10-20hp, the gauge animation will only last a small fraction of a second, too subtle to notice. I think the old gauge position should be kept momentarily, and the animation delayed. See this from guilty gear as an example: https://youtu.be/r_xYdKaIyNM?t=59s

What do you think?

**Comment by flags** [comment]
That crossed my mind when I was testing it. Only solution I could think of
was tracking some kind of damage delay variable that reset to some upper
limit each time a player took damage. After that timer hit 0 the current
behavior would become active. I have a few other methods that might work
also. I'll do some tests this weekend and see what works best!
