### ISSUE TITLE
Female / other race screams

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#371]
Instead of the male-only death sounds, have:
- Female versions (for LADY only; more female characters in future possibly)
- Alien (chorus screams?)
- Ogre (deeper pitch)
- Monster
- Helmeted (walkie talkie voice)
##

**Comment by sauer2** [comment]
Something among those: http://opengameart.org/art-search?keys=scream ?

**Comment by cxong** [comment]
Some of those are ok. Ideally I would like at least 4 variations per voice, otherwise it gets too repetitive, but I don't think there's enough there yet... better start collecting.

**Comment by sauer2** [comment]
@cxong BTW doesn't the same apply to the "OK" rescue sound?

**Comment by cxong** [comment]
Good point; actually I was trying to find a good sound effect for the "rescue" thing when I came across the "OK" sound, I didn't mean to imply it's something the hostage says, it's even in a different voice - a radio voice. But I guess it would be a problem once we have different voices but the rescue sound effect is still a male radio.

Maybe I'll replace it with a generic "ding" sound effect, unless you can think of a sound that implies "rescue"? Or we'll have to look for different voices saying "OK" or similar, which is harder.

**Comment by sauer2** [comment]
I think it may be best to replace it with a DING sound. Alternatively
one could create a "You got the hostage" radio effect, but that might
not fit to some situations.

Am 01.04.2016 um 01:53 schrieb Cong:
