### ISSUE TITLE
Continuous Collision Detection

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#372]
To make collision more robust and avoid tunneling bugs, we can implement Continous Collision Detection.

For C-Dogs and its axis-aligned objects, this is a bit easier; one possible solution is found here: http://gamedev.stackexchange.com/q/55873/26250

*Formerly: Recoil can push enemies through walls*

Reproduce using flamer against asbestos enemies

Collision detection should run at least once per tile, for impulse movement
##

**Comment by cxong** [comment]
Actually, thinking about this, the reason why asbestos enemies has this bug is because the flame is colliding and pushing them every frame - which shouldn't be the case. Perhaps the flame shouldn't push these enemies at all? Or somehow add a flag/timer so that asbestos enemies are not pushed repeatedly.

**Comment by sauer2** [comment]
@cxong This also happens in the second campaign I sent you by mail in the third last level.
To reproduce pick up a MP and shoot at Nexus while it is standing nearby a wall.
