### ISSUE TITLE
Replacement campaigns

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#385]
Eventually we want to make C-Dogs SDL 100% free (#336), but that means removing the classic C-Dogs campaigns as they are not free.

This is bad because C-Dogs is not much of a game without campaigns. At minimum, we should replace the classic campaigns with an equivalent amount and diversity of campaigns.

The original game features 5 campaigns (2 built-in, 3 as external files) of equivalent length:

- Between 10 and 20 missions
- At 2-3 minutes per mission, this represents 30-60 minutes of gameplay, not counting retries
- Altogether that's up to 5 hours of content

The campaigns are also quite varied:

- Bug-eyed monsters: absurd story, weird weapons, this one showcases the features of C-Dogs
- Ogre Rampage: serious thriller story, lots of pitched battles with good NPCs too, this one showcases the (compared to Cyberdogs) campaign plot and better AI
- Distress: interesting build-up story, horror themes
- terror: focus on gunplay as enemies shoot a lot
- zombies: zombies!

So a good replacement set of campaigns should feature:

- [ ] >5 hours of content, preferably with >30 minutes per campaign
- [x] A techno-thriller/military story
- [ ] Zombies
- [x] Pitched battles between lots of friendly and enemy AIs
- [x] Missions with intense gunplay
- [ ] Horror/tension
- [ ] Weird/novel weapons

So far, we have the following campaigns, but we need more (or improvements):

**Sand**

- [x] Techno-thriller
- [x] Pitched battles
- [x] Intense gunplay

Could really be improved with:

- [ ] Weird weapons

**Doom**

Unfortunately not a very C-Dogs-like campaign, just lots of shooting mooks.

**Comment by sauer2** [comment]
@cxong Right now I can't promise much, still, maybe I could create one of my campaigns or modify one, to fit those criteria more than before.

Any ideas on what to do ideally?

**Comment by cxong** [comment]
My favourite campaign of yours is space pirates; it has a nice variety of missions, good story and good balance. I think it can be improved by making it longer.

Devhell also has a pretty funny premise, but I think it's too short.

I'll try to replay those campaigns some time, it's been a while and I can't remember all of them.

**Comment by sauer2** [comment]
Ok, so until further feedback, Space Pirates it is.
Like I said, I can't promise anything right now, but maybe there is time 
for me to work on the campaign next week.

Am 26.03.2016 um 14:02 schrieb Cong:

**Comment by sauer2** [comment]
@cxong BTW: Devhell somehow doesn't play the included songs. Did you unimplement this feature or is this a bug?

**Comment by cxong** [comment]
Looks like a bug; issue created here #389

**Comment by sauer2** [comment]
@cxong 
I started working on a campaign that replaces "YOU are the experiment" part I and II. My plan is to work on them in parallel to prevent bigger deviations in style and quality. Just so you know that it might take a little longer to finish the space pirate campaign.

**Comment by sauer2** [comment]
@cxong 
I sent you a first complete version of the space pirate campaign by mail.

**Comment by cxong** [comment]
Since Ronny has released all his assets under CC-BY, there's no need to replace the original campaigns, although new ones will still be good. To make C-Dogs SDL fully free now, we just need to exclude the custom campaigns with unknown licenses (cpns, AnttiHukkanen etc.), and offer them as a separate download pack.
