### ISSUE TITLE
Recolour replacement sprites

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#388]
This should help make the look of the new graphics more consistent with the original game.

Here's the palette: 
![palette](https://cloud.githubusercontent.com/assets/1083215/13985334/4d0dec08-f150-11e5-9e94-2fc26613fcc3.png)
##

**Comment by sauer2** [comment]
In the end, it's up to you.
But I want to note that I like the new graphics as they are better, since they look somewhat crispier.

**Comment by cxong** [comment]
Thanks; I think they're mostly good too, but there are a few that definitely have colours that look out of place. There are some I adapted from a pokemon-like pack and some realistic packs but without recolouring, and the colours are too bright and pastel-like or too dark and indistinct. I'd like to try recolouring them to see if they will look better.

**Comment by cxong** [comment]
Check out this recoloring tool: http://withthelove.com/ppt/

**Comment by cxong** [comment]
Well the results were less exciting than I thought 😓 I guess the C-Dogs palette had too many colours to really make a difference

**Comment by cxong** [comment]
<img width="551" alt="Screen Shot 2019-11-17 at 8 08 00 pm" src="https://user-images.githubusercontent.com/1083215/69005580-449bad00-0978-11ea-8d64-43182d1b46de.png">
