### ISSUE TITLE
Remove obsolete campaigns?

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#394]
The following might sound a little like I'm the big exclusionist, but in my experience bad content drags down a game in a number of ways.

And let's face it, right now C-Dogs is distributed with a lot of campaigns that have zero redeeming qualities. As in, zero mission gameplay value, zero arcade gameplay value, no common theme, no atmosphere, nothing.

There are:

- redundant files (I think there is even a copy of one of the original campaigns in the first cpns dir.)
- one-mission campaigns that could be randomly generated, but randomly generated missions are more interesting, even when it comes to arcade gameplay
- big, random campaigns with huge maps with tons of objective objects, again, quick games are better
- things that might or might not work, like many of the totally phukt up missions
- campaigns that try to mimic network gameplay, with inane characters

Thoughts?

**Comment by cxong** [comment]
Yes; there's a lot of crap campaigns :smile: I'd rather not have to pick the bad ones from the good though. Here's what I was thinking:

- Put the non-official ones more out of the way, in a subfolder
- Make them optional downloads - this will be done anyway with #385 

So eventually the campaign menu will look like this:

- `cdogs-sdl-campaign-1`
- `cdogs-sdl-campaign-2`
- `cdogs-sdl-campaign-3`
- `cdogs-sdl-campaign-4`
- `cdogs-sdl-campaign-5`
- `custom/`
  - `sauer2/`
    - `campaign1`
    - `campaign2`
    - `campaign3`
 - `Wuzzy/`
    - `gungame`
 - `techdemo/`
    - `demo1`
    - `demo2`
    - `demo3`

...and so on. Optionally, they can download a "classic mission pack", which adds this entry:

- `custom/`
  - `classic/`
    - `ogre`
    - `bem`
    - `bad`
    - `distress`
    - `zombies`
    - `ogre`
    - `cpns/`
      - _weird campaigns go here_

**Comment by sauer2** [comment]
@cxong The options with the downloads is the best, I think. Especially if there is some kind of "unsupported third-party content" disclaimer on it.

Are you planning to eventually add a download manager into the game itself?

**Comment by cxong** [comment]
Just a link to the extra campaigns on the website.
