### ISSUE TITLE
autosave.cnf gets corrupted in some rare cases

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#395]
When that happens it leads to a core dump which shows a memory map at the next start.

**Comment by cxong** [comment]
I've rewritten some path processing code which was causing some similar issues with the autosave file on my end, but I don't know if it's the exact same issue you have. So please help me confirm that this has been fixed:

- Before doing anything, take a look at your current autosave, the one that causes crashes; do the paths look wrong, like `../../../../../../..` in them?
- Before updating the game, play through a level (so that the autosave is created). Does the new autosave still look wrong?
- Delete/rename the autosave, update the game, and play through a level. Does the path look correct in the new autosave?

**Comment by sauer2** [comment]
`Before updating the game, play through a level (so that the autosave is created). Does the new autosave still look wrong?`

Yes, they looks like "Path": "../../../../issions/spacepirates.cdogscpn"

Is it normal that the 'm' is missing?

However, I can't reproduce the crash right now, it might be linked somehow to the faulty index I had in the space pirates mission before.

**Comment by sauer2** [comment]
It also seems like the dot dot slash part gets longer:

`{
	"Version": 2,
	"LastMission": {
		"Campaign": {
			"Path": "../../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "412o59",
		"MissionsCompleted": 1
	},
	"Missions": [{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "412o59",
		"MissionsCompleted": 1
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "klgp59",
		"MissionsCompleted": 2
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "06vq59",
		"MissionsCompleted": 3
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "gq9s59",
		"MissionsCompleted": 4
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "waot59",
		"MissionsCompleted": 5
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "cv2v59",
		"MissionsCompleted": 6
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "sfhw59",
		"MissionsCompleted": 7
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "80wx59",
		"MissionsCompleted": 8
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "okaz59",
		"MissionsCompleted": 9
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "412o59",
		"MissionsCompleted": 1
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "klgp59",
		"MissionsCompleted": 2
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "06vq59",
		"MissionsCompleted": 3
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "gq9s59",
		"MissionsCompleted": 4
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "waot59",
		"MissionsCompleted": 5
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "cv2v59",
		"MissionsCompleted": 6
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "sfhw59",
		"MissionsCompleted": 7
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "80wx59",
		"MissionsCompleted": 8
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "okaz59",
		"MissionsCompleted": 9
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "okaz59",
		"MissionsCompleted": 10
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "412o59",
		"MissionsCompleted": 1
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "klgp59",
		"MissionsCompleted": 2
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "06vq59",
		"MissionsCompleted": 3
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "gq9s59",
		"MissionsCompleted": 4
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "waot59",
		"MissionsCompleted": 5
	},
	{
		"Campaign": {
			"Path": "../../../.././../../.././../../../issions/spacepirates.cdogscpn"
		},
		"Password": "412o59",
		"MissionsCompleted": 1
	}]
}`

**Comment by cxong** [comment]
Could you please try again with the latest version?

- The last version was still broken
- This one shouldn't keep adding the `../..`s
- The autosave is updated simply by quitting the game, no need to play through a level to test

**Comment by sauer2** [comment]
I think, you fixed it now.
It looks like

`{
	"Version": 2,
	"LastMission": {
		"Campaign": {
			"Path": "missions/spacepirates.cdogscpn"
		},
		"Password": "gq9s59",
		"MissionsCompleted": 4
	},
	"Missions": [{
		"Campaign": {
			"Path": "missions/spacepirates.cdogscpn"
		},
		"Password": "gq9s59",
		"MissionsCompleted": 4
	}]
}`

which seems correct to me. Also, the continuing feature works correctly now.
Good job.

**Comment by cxong** [comment]
thanks for checking :+1:
