### ISSUE TITLE
Random core dump

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#398]
This happens sometimes, with a tendency towards coop mode.

May be related to keyboard input.

**Comment by cxong** [comment]
Could you please provide more details? Like how to reproduce?
If it's hard to reproduce, try running with debug logging and saving the log file e.g. `./cdogs-sdl --log=DEBUG > debug.log`

**Comment by sauer2** [comment]
@cxong I can't reproduce it. It's really random.
Guess I should run in logging mode from now on...

BTW: The log file that created didn't write clear text but lots of 

> [22;37m

**Comment by cxong** [comment]
Those are ascii colour codes for coloured logs in the terminal; I should check if the output is a terminal and not print colours in that case.

**Comment by sauer2** [comment]
@cxong It's just that there is nothing else, apart from the C-Dogs welcome message.

**Comment by cxong** [comment]
Oh my bad, the logs are to stderr; so it should be `./cdogs-sdl --log=DEBUG 2> debug.log`

**Comment by sauer2** [comment]
@cxong I haven't encountered this anymore and I guess this was solved with either the configuration fix or the indexing fix.

**Comment by cxong** [comment]
Thanks; strange bug :ghost:
