### ISSUE TITLE
saving a character template corrupts players.cnf file

### ISSUE THREAD

**Issue by noerw** [cxong/cdogs-sdl#406]
when a character template is saved, some savefile corruption occurs, resulting in a crash once i try to start a game the next time.

sometimes some weird unicode characters appear in `players.cnf`:
```
{
	"Version": 2,
	"PlayerTemplates": [{
		"Name": "Omniflash",
		"Face": "�E \u0011",
		"Body": "c51b9e",
		"Arms": "46b2aa",
		"Legs": "c269d0",
		"Skin": "7ad6be",
		"Hair": "f7e941"
	}]
}
```

sometimes parts of `options.cnf` appear in `players.cnf`:
```
{
	"Version": 2,
	"PlayerTemplates": [{
		"Name": "Trisphere",
		"Face": "erHP\":100,\"FirstTo\":5},\"Graphics\":{\"Brightness\":0,\"Fullscreen\":false,\"ResolutionWidth\":320,\"ResolutionHeight\":240,\"ScaleFactor\":2,\"ShakeMultiplier\":1,\"ScaleMode\":\"Nearest neighbor\",\"OriginalPics\":false},\"Input\":{\"PlayerCodes0\":{\"left\":80,\"right\":79,\"up\":82,\"down\":81,\"button1\":40,\"button2\":229,\"map\":43},\"PlayerCodes1\":{\"left\":92,\"right\":94,\"up\":96,\"down\":90,\"button1\":98,\"button2\":88,\"map\":99}},\"Interface\":{\"ShowFPS\":false,\"ShowTiP\u0003",
		"Body": "a82e0a",
		"Arms": "ba59e2",
		"Legs": "6a09b6",
		"Skin": "e706dd",
		"Hair": "fac81b"
	}]
}
```

the console output when starting the next game is

    ERROR [MAIN ] [character_class.c:55] StrCharacterClass(): Cannot find character name: erHP\":100,\"FirstTo\":5},\"Graphics\":{\"Brightness\":0,\"Fullscreen\":false,\"ResolutionWidth\":320,\"ResolutionHeight\":240,\"ScaleFactor\":2,\"ShakeMultiplier\":1,\"ScaleMode\":\"Nearest neighbor\",\"OriginalPics\":false},\"Input\":{\"PlayerCodes0\":{\"left\":80,\"right\":79,\"up\":82,\"down\":81,\"button1\":40,\"button2\":229,\"map\":43},\"PlayerCodes1\":{\"left\":92,\"right\":94,\"up\":96,\"down\":90,\"button1\":98,\"button2\":88,\"map\":99}},\"Interface\":{\"ShowFPS\":false,\"ShowTiP\u0003

**Comment by cxong** [comment]
Thanks for reporting :+1:
