### ISSUE TITLE
pickups occassionally don't work when playing in Dogfight/Deathmatch mode

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#407]
They are spawned, but one can not pick them up.

**Comment by cxong** [comment]
How can this problem be reproduced?

**Comment by sauer2** [comment]
I'm not sure, but this may happen when playing Suicidal Tendency by Traut over LAN.

**Comment by cxong** [comment]
You cannot pick up ammo if you don't have a gun that uses it. I was thinking about single player for this - don't want players to steal each other's ammo if they won't use it anyway. Maybe this doesn't make sense for PVP? Or is this too confusing?

**Comment by sauer2** [comment]
@cxong It completely makes sense, but I couldn't actually pickup my own ammo as well, leading to the player who had a knife to win.

**Comment by sauer2** [comment]
@cxong Actually, it's not a LAN related problem. It always happens.

To reproduce:

1. Have ammo activated.
2. Play a dogfight round of spells n spikes against a splitscreen player.
3. Start a deathmatch in Trauts Suicidal Tendencies against a splitscreen player.

**Comment by cxong** [comment]
Thanks for chasing this up; I think we are very lucky to have caught this: see the commit for details 🙆
