### ISSUE TITLE
Editor crashes when selecting wall/floor/room color

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#413]
Reproducable in every level. Not critical, can be worked around in a text editor.

Stack trace:
```
Core was generated by `./cdogs-sdl-editor ../missions/custom/sauer2/antares3consp.cdogscpn'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000042e5db in Blit (device=0x70b9c0 <gGraphicsDevice>, pic=0x0, 
    pos=...) at /home/clemens/Projekte/cdogs-sdl/src/cdogs/blit.c:181
181		Uint32 *current = pic->Data;
```

@cxong  BTW: Since working on spells_n_spikes works for you (it still doesn't over here), could you please

* remove shuriken from the player start weapons
* remove crossbow and blunderbuss from the map weapons and add them to the player start weapons (they are pretty weak in comparison)
* add shuriken to the map weapons and place all map weapons in a way that makes the most sense to you

?

**Comment by sauer2** [comment]
It seems the crash is only triggered when selecting the colour from the palette. Entering a color code works.

**Comment by cxong** [comment]
I've made the changes to spells and spikes but I think it should be fixed before the next release. Could you provide a way to reproduce it, with a full stack trace? Maybe I can guess at what the problem is just from that. Otherwise, I'm assuming this is in linux, I'll try to reproduce it there.

**Comment by cxong** [comment]
I've managed to reproduce the problem, and know what the cause is. Fix may take a while though.

**Comment by sauer2** [comment]
@cxong Thanks.
BTW: I sent you an update of another map by mail.
