### ISSUE TITLE
Minor editor bug: free color selection doesn't work on character properties

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#415]
The text field can't be edited.

Also a minor feature request: In the level related color selectors you have to click a color button or somewhere else in the editor to close the dialog. It's kind of annoying for experimentation, though. A small close button to close the dialog would be a better option.
Same with the weapon selection dialog.

**Comment by sauer2** [comment]
Another minor issue: If you use the new room brush at the bottom of the map the editor crashes.

**Comment by cxong** [comment]
Thanks for reporting :+1:
