### ISSUE TITLE
Feature suggestion: show score in deathmatch in game

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#416]
It would be cool to be able to see how many lives your opponent has left.

Are there drawbacks regarding the gameplay?

**Comment by cxong** [comment]
I assume this is for network play; where should it be shown? I think it could be folded into #284

**Comment by sauer2** [comment]
Whoops, forgot to mention it's for network play...

Maybe on the right side, so it's kind of symmetric to your own life indicator?

**Comment by cxong** [comment]
![screen shot 2016-07-10 at 9 20 13 pm](https://cloud.githubusercontent.com/assets/1083215/16713233/341e5216-46e4-11e6-8250-78ad9d620e7e.png)

**Comment by sauer2** [comment]
Neat, thanks!
