### ISSUE TITLE
return to main menu after leaving a scenario

### ISSUE THREAD

**Issue by noerw** [cxong/cdogs-sdl#417]
Currently one returns to the menu "select a scenario/campaign", which is especially weird when leaving a multiplayer game as client.

Returning to the "start" or "main" menu is more intuitive i think

**Comment by cxong** [comment]
I put this in because if you want to play another map, it would be tedious to navigate the start/campaign menus again. But I agree that this makes no sense for a client, so I think I'll add an exception for that.
