### ISSUE TITLE
Restore and extract original graphics

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#421]
Now that C-Dogs assets have been opened, we ought to go back to the original graphics so that the original campaigns looks exactly as before, providing a more authentic experience. The new graphics can still be there, but in addition to the originals.

The original graphics should also be extracted from the .px binary blobs into separate, organised image files. This is a prerequisite for extending them, as it's much easier if they've been refactored to use spritesheet rendering, for example.

Unfortunately this may involve lots of other work; this issue will be broken up as we go.

Some subtasks:

- [x] Tiles
- [x] Map objects
- [ ] Actors (related to #69)
- [x] Pickups
- [x] Keys, exit tiles
- [x] Bullets
- [ ] Font
- [x] Doors

And since Cyberdogs data is also CC-BY, they can be included too:

- [ ] Heads

**Comment by sauer2** [comment]
@cxong does that make the new graphics another theme?

**Comment by cxong** [comment]
No, they will be available as separate tiles, objects etc.

**Comment by sauer2** [comment]
@cxong Hm, lets hope they don't look too different, because that might screw with the look of some missions. In particular the cabin/save/black_crate graphics which double as computer components.

Oh, and btw, I attached the stack trace; just in case you didn't get a message because I put that @ thing there in an edit step.

**Comment by cxong** [comment]
Yes, if necessary you can do a search/replace in your campaigns. In most cases I think the names make more sense for the original graphics so I'll give the new graphics different names. As part of this issue, I'll also make sure you can add custom tiles, objects etc so if you can find better graphics, you can use those too.

**Comment by sauer2** [comment]
Thanks, will do.

**Comment by cxong** [comment]
Split remaining subtasks
