### ISSUE TITLE
Optimise for GCW-Zero

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#422]
Performance should have been greatly improved after the SDL2 port, at least for high screen resolutions. However, the game still runs at 30fps, including some choppiness, on GCW-Zero.

C-Dogs is still fundamentally a simple game, so it's likely that the game is simply doing some inefficient things, and may be able to run the full 70fps. Do some profiling using 320x240 resolution, and see what the bottlenecks are.

**Comment by carstene1ns** [comment]
I have not looked at the source code since the SDL2 port yet, but just a random thought:
Is VSYNC enabled? It may be either in C-Dogs or SDL2 itself. This can cause a major slowdown.

**Comment by cxong** [comment]
vsync shouldn't be set; I'm using `SDL_CreateWindowAndRenderer` which does not accept vsync flag.

**Comment by cxong** [comment]
Some fixes for next release:

- [ ] crash in dogfight/doom, dogfight/map01, deathmatch/doom, dogfight/map01
- [ ] include copyright status of all campaigns

**Comment by cxong** [comment]
It seems fps is still about 30, despite the recent optimisations. It can be raise to 40 if blood is turned off.
It might be harder to optimise from this point on; the next candidate would be things like #440 and removing all the per-pixel draw calls. Some game code could be optimised too; 4 player deathmatch only runs at 5 fps.
