### ISSUE TITLE
Distribute Windows .zip

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#425]
Current packaging uses CMake/CPack, which builds an installer for Windows.

As a .zip file, the game can then be played even if installation is not allowed or desired on a computer. Maybe also include shortcuts in the root dir since the executables are under `bin/`.

**Comment by TheCodeArtist** [comment]
Assuming this needs to be done for every release,

Can this be automated as a script that: 
- Executes the release setup.exe 
- Adds/Modifies files within the installation directory
- zips up the installation directory as a self-contained portable zip.

**Comment by cxong** [comment]
Please see `CMakeLists.txt`, which contains packaging code for creating various installers. This task is to extend this to also produce a zip archive for Windows.
