### ISSUE TITLE
Gray colouring of the terminal font upon closing

### ISSUE THREAD

**Issue by akien-mga** [cxong/cdogs-sdl#426]
Hi there,

I've noticed that when I close cdogs-sdl, the font of my terminal turns gray (see the last line):
![spectacle b11320](https://cloud.githubusercontent.com/assets/4701338/15700859/e4bbfcf4-27d6-11e6-96fd-475343d57b97.png)

I imagine that you have some code that changes the font colour for the log output, but you're not resetting it to the right one in the end. I think you'd need to use `[39m` to reset to the user-defined colour: http://pueblo.sourceforge.net/doc/manual/ansi_color_codes.html

**Comment by akien-mga** [comment]
It seems also to happen after ``CampaignLoad()``:
![spectacle v11320](https://cloud.githubusercontent.com/assets/4701338/15700982/aabbef2c-27d7-11e6-83ff-7403c9c098ca.png)

**Comment by cxong** [comment]
Thanks for raising; I haven't tested but it was an issue with an upstream lib.
