### ISSUE TITLE
Number animations in mission end screen

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#428]
It will be more exciting if the score numbers in the mission end screen animated from 0 to their actual value, with ticking sound effects, similar to the mission briefing text animation. Once the animation is done, the "Continue" menu items are shown; before the animation is done, button presses will end the animation.

The speed of the animation should be adaptive, so that large numbers don't take forever to animate. One way to do this is to animate logarithmically, for example animate the number up to 50%, then up to 75%, 87.5%... etc, with each step taking the same amount of time.

**Comment by sauer2** [comment]
@cxong 

>The speed of the animation should be adaptive, so that large numbers don't take forever to animate. One way to do this is to animate logarithmically, for example animate the number up to 50%, then up to 75%, 87.5%... etc, with each step taking the same amount of time.

Could you also do that to the healthbar change rate? It's kind of slow if the player takes a lot of damage...

**Comment by cxong** [comment]
![score_animation](https://user-images.githubusercontent.com/1083215/50383897-3bc33c80-0711-11e9-91cd-3e6a1276d3d0.gif)
