### ISSUE TITLE
Editor: Map object selection menu gets clipped by bottom window border

### ISSUE THREAD

**Issue by chack05** [cxong/cdogs-sdl#429]
As much as I like the new selection menu for map object - in fact, I'd like to see it for objectives as well, it's positioned in a way that it's too big to show on my screen. Even when using the whole screen, about a third of it gets cut off.

Same nearly happens with the pickup menu, if there are many custom weapons.

**Comment by cxong** [comment]
I think I'll add pagination to that menu.

**Comment by sauer2** [comment]
Thanks.

For now, I see you moved the popup origin closer to the window origin.

This helps, but somehow some objects can't be clicked on and instead the click triggers another text button below the popup.

**Comment by cxong** [comment]
@sauer2 that problem is fixed.

**Comment by sauer2** [comment]
@cxong Confirmed, thanks!
