### ISSUE TITLE
Crash in the Doom campaign related to new hex tiles

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#435]
For both, trying to play and opening with editor I get

`Cannot load non-32-bit image: Success
Only 32-bit depth images supported (tile/hex/shadow)
Cannot load non-32-bit image: Success
Only 32-bit depth images supported (tile/hex/alt1)
Cannot load non-32-bit image: Success
Only 32-bit depth images supported (tile/hex/alt2)
Cannot load non-32-bit image: Success
Only 32-bit depth images supported (tile/hex/normal)
`

followed by a crash as

`cdogs-sdl-editor: /pathtoit/cdogs-sdl/src/cdogs/pic_manager.c:961: PicManagerGenerateMaskedPic: Assertion 'original != ((void *)0)' failed `

**Comment by cxong** [comment]
Thanks for raising :+1:
