### ISSUE TITLE
Extracted gun picture not shown

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#450]
However, the knife picture is shown.

**Comment by cxong** [comment]
Thanks; I'm in the middle of working on #441 which is a big chunk of work, so things are broken until that's done. For example the gun picture is fixed but the muzzle offset is still broken.

**Comment by sauer2** [comment]
@cxong confirmed fix

BTW: I sent you another mail, since the second mail about the "temple of carnage" map apparently got lost or spam filtered or something.
