### ISSUE TITLE
Level warp

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#451]
Normally C-Dogs campaigns go through a linear series of maps/levels. With the ability to warp between arbitrary levels, we can:
- implement "secret" levels - e.g. normally a campaign has levels 1-8, but warping allows a player to go say from level 4 to level 9, then from level 9 to level 5
- implement branching storylines

There's the question of how to select the warps:
- Most logical approach would be multiple exits, but this means it's only really usable for static map types, where we could hide certain exits behind keys, unless:
- We associate certain objectives with certain exits. The normal exit appears when you complete all required objectives, but we could generalise that, e.g. for objectives A, B, C, exit 1 appears when A and B are completed, exit 2 appears when B, C are completed and so on.
- Or maybe other triggers for exits? The objectives are probably enough for now.
- What about hidden exits? Ones that don't appear on the compass or automap...

**Comment by sauer2** [comment]
@cxong Combined with the other stuff we considered in emails - timers, floor triggers, etc - that would get complicated pretty fast. How do you want to handle this in the editor? Some kind of graphical scripting language?

**Comment by cxong** [comment]
Scripting languages is probably overkill. I think adding them gradually is fine, especially considering these features are probably years off unless they are prioritised.

**Comment by sauer2** [comment]
@cxong Probably right, I just hope the editor interface doesn't get too messy with that amount of small various options.

**Comment by cxong** [comment]
![levelwarp](https://user-images.githubusercontent.com/1083215/87246924-dd48e500-c493-11ea-82a6-5960c29405e2.gif)
