### ISSUE TITLE
Rewrite character editor

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#462]
Some kind of editor wishlist:
- Opaque background for the main editor dialog, because drawing levels would be easier with visual constraints, like described by mail.
- Putting all character editor options in a nice, multi-column, tabular form. Right now some of the labels and buttons overlap slightly.

**Comment by cxong** [comment]
I'm thinking of rewriting the character editor using a proper GUI framework; I would have liked to do the same for the editor itself but it's probably too much work, but the character editor might be a good start.

**Comment by cxong** [comment]
Currently looking at rewriting the character editor using nuklear. There is no plain SDL backend though, so I'm experimenting with how to draw pixels with opengl, in a way that integrates well with nuklear.
