### ISSUE TITLE
Native file open/save dialogs for editor

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#463]
Something cool to try: https://github.com/mlabbe/nativefiledialog

**Comment by sauer2** [comment]
@cxong Won't you have native dialogs anyway once you create a new character editor?
Assuming you use something like libgui.

**Comment by cxong** [comment]
This one will just be for the campaign editor, which I probably won't rewrite because it will be a lot of work.

**Comment by cxong** [comment]
Giving up; this library requires too much build system changes (C++, MSVC required)

**Comment by cxong** [comment]
Try https://github.com/AndrewBelt/osdialog

**Comment by cxong** [comment]
![ezgif-1-a3a144ac8cea](https://user-images.githubusercontent.com/1083215/71964518-d4abf380-3251-11ea-9e7b-1d8b03985b4d.gif)
