### ISSUE TITLE
Campaign options

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#495]
Editor and map format support for custom campaign options:

- Ammo
- Random pickups from destroyed map objects
- Default player template

**Comment by sauer2** [comment]
Could it be possible for you to add support for specific pickups from destroyed map objects that are part of a pickup objective?

For example, I'm working on this campaign where in the first mission you shatter some rocks and pick up some ore samples. It would be a tad bit cooler if the player gets the ore samples from destroying the rocks...

[harmful_crysalis.cdogscpn.zip](https://github.com/cxong/cdogs-sdl/files/913837/harmful_crysalis.cdogscpn.zip)

**Comment by cxong** [comment]
That will be a tricky feature to do right. Depends on what you want.

- All the objective markers, highlights etc will have to apply to the map object as well as the pickups, even though the map objects aren't part of the objective. Will this conflict with destroy objectives? Not sure.
- The way pickups from destroyed map objects currently works is that there's a random chance for a class of map objects to drop certain kinds of pickups, so ammo, gun, health.
  - How will this work for objectives - would they have to specify a specific pickup instead of a pickup class? E.g. instead of "drop ammo", it'll be "drop shotgun shells", or "drop objective id 3"
  - Does it even make sense to store this information per class of map object? Is it better to mark specific map objects as dropping something? I.e. normally a safe might drop ammo, but this specific safe on this level drops objectives. This will require editor support.
  - Do we even want the drop chance to be random? Or maybe just always drop objectives (and how many? One? Many?) Because if the chance is random, there's a chance that not enough objectives are dropped, making the objective (and maybe mission) impossible to complete. And this also means there are now three ways to place objectives: randomly (classic C-Dogs), in fixed locations (static map type), and now dropped from destroyed map objects. We'd want to rework the objective placement logic, and most likely editor, to make this more generic and clear. The current implementation is a bit of a hack.

**Comment by sauer2** [comment]
I thought of option 1.
Now that you mention it though, the whole idea probably conflicts too much with the markers logic.

Would this work as a new objective type?

**Comment by cxong** [comment]
New objective type won't solve the issues mentioned.

I now think it might be a mistake to have random spawning of pickups. It's much better if it's consistent, so that players quickly learn to expect that certain map objects will drop certain pickups. This will work best with custom map objects, and not so much with the original C-Dogs map objects. So for example a safe will always drop money, an ammo locker will always drop ammo. I've been thinking of adding a "use" command to the game, so you can interact with map objects, like open safe, type on computer etc. So another way of getting the pickup drop would be to use/open the map object instead of destroying it. I think all this will work well once they're all in place.

**Comment by sauer2** [comment]
>I've been thinking of adding a "use" command to the game, so you can interact with map objects, like open safe, type on computer etc. So another way of getting the pickup drop would be to use/open the map object instead of destroying it. I think all this will work well once they're all in place.

Sounds cool. Will it be possible to use the run/switch weapon key for this action?

**Comment by cxong** [comment]
Yes, it will also make things better because right now it's only used to pick up guns.

All this stuff is quite a ways off. Do you think you can implement the objective some other way? You can actually place map objects over pickups right now, would that be ok as a workaround?

**Comment by sauer2** [comment]
>All this stuff is quite a ways off. Do you think you can implement the objective some other way? You can actually place map objects over pickups right now, would that be ok as a workaround?

That would work I guess. That being said, I'm fine with leaving it two separate objectives. That could count as some different type of analyses. I don't know enough about geology that it makes a difference to me, to be honest. :japanese_goblin:
