### ISSUE TITLE
Everything compiled fine

### ISSUE THREAD

**Issue by liketofight69** [cxong/cdogs-sdl#506]
but when i run it I get the "could not initialize sdl. No available video device." on ubuntu 16.04 32 bit. I installed all the necessary libraries and have set the video device. I think it might be a compatability issue.

**Comment by cxong** [comment]
Try installing `cdogs-sdl` from the playdeb repo http://www.playdeb.net/app/cdogs-sdl
This should install the right dependencies. Then see if the game works.
