### ISSUE TITLE
"Level Select" level selection menu leads back to campaign selection...

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#508]
... instead to the level briefing screen.

**Comment by cxong** [comment]
This should be fixed already

**Comment by sauer2** [comment]
It's still there, though.

Steps to reproduce:

1. Select level of a campaign (works the first time)
2. Exit the game (or lose the game)
3. Try again to select a level -> you get to the campaign menu

**Comment by cxong** [comment]
I can't reproduce it:

- Start Harmful Crysalis, level 2
- Quit game immediately after starting game
- Go back into Harmful Crysalis, level 2
- Campaign loaded, starting from Game Options screen

**Comment by sauer2** [comment]
@cxong Apparently it only happens if you lose the first game. My mistake.

**Comment by cxong** [comment]
thanks, found the problem now 👍

**Comment by sauer2** [comment]
No problem ;)
