### ISSUE TITLE
Emscripten cleanups

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#512]
Follow up from #208 

- [ ] Some sound effects missing
- [ ] Save files
- [ ] Publish to itch.io
- [ ] Update website
- [x] Remove `main()` from `src/XGetopt.c`, `src/cdogs/c_hashmap/main.c`
- [ ] Test joysticks
- [x] Fix `Mix_SetPosition`
- [x] Move `cdogsed.c` to subfolder, remove `__EMSCRIPTEN__` define
- [x] Fix frame rate
- [x] Better default keyboard controls
- [x] Console colours
- [x] Fix keyboard remapping screen

**Comment by dorkster** [comment]
About the missing sound effects and `Mix_SetPosition()`: I think we're at the mercy of the Emscripten port of SDL_Mixer in both cases. I initially though that the missing sound effects might be solved by building with `USE_OGG=1` and `USE_VORBIS=1`, but I had no luck.

I wouldn't worry too much about the console colors. You can eventually create a simpler html template that doesn't have a visible console (plus browser's have there own JS console). It also ends up looking nicer when embedded on itch.io. You can look at what I did for [Freeblocks](https://dorkster.itch.io/freeblocks) as an example.

**Comment by cxong** [comment]
Abandoning - emscripten would be nice but a lot of features depend on local install, like settings, custom campaigns etc. Let's focus on publishing to more storefronts instead
