### ISSUE TITLE
[Question] Changed enemy AI

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#514]
Was the enemy behavior changed lately? Maybe a reduction of movement?

It seems that foes are sometimes more passive than before...
This is in particular weird in missions with peek-a-boo doors like the doom campaign where nothing comes out of the doors.

**Comment by cxong** [comment]
I'm not so sure about being more passive, but the doors definitely don't open instantly as before. Not sure when that happened.

If you know what to look for, you can try a git bisect to see exactly which commit caused the problem.

**Comment by sauer2** [comment]
It seems to be [this](https://github.com/cxong/cdogs-sdl/commit/ff49132dbf906f3784fb235038859c238f064723) commit.

Somewhat reliable indicators to check:
- in DOOM level 8 in the siderooms of the second chamber the monsters won't move for quite a while after this commit
- in Harmful Crysalis level 2 the aliens behind the cabinet will run around but almost never stab you, unlike before the commit

**Comment by sauer2** [comment]
@cxong Seems fixed now. Thanks!
