### ISSUE TITLE
Higher resolution program icon

### ISSUE THREAD

**Issue by Mailaender** [cxong/cdogs-sdl#522]
https://github.com/cxong/cdogs-sdl/tree/master/build/linux has 48px max which isn't big enough and therefore won't get displayed on modern Linux menus.

**Comment by cxong** [comment]
What resolutions are required?

**Comment by Mailaender** [comment]
64x64, 128x128 and 256x256 seem to be standard nowadays. If you have a source file, a scalable one ready a .svg would solve the problem once and for all.

**Comment by hashar** [comment]
As of current master ( ea0651ca5b17538e4bff8694edbc8b43259cee63 ):

16x16: ![16x16](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/linux/cdogs-icon.16.png)
22x22: ![22x22](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/linux/cdogs-icon.22.png)
32x32: ![32x32](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/linux/cdogs-icon.32.png)
48x48: ![48x48](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/linux/cdogs-icon.48.png)
128x128: ![128x128](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/linux/cdogs-icon.128.png)

Note how icons 16, 22, 32 are different from the 48 and 128 ones. It seems the 128 pixel ones has just been scaled up from the 48 px one.

There are other icons as well:
build/macosx/cdogs-icon.icns
build/windows/cdogs-icon.ico (16, 22, 32, 48)

build/gcw-zero/cdogs-sdl.png 32px ![gcw-zero 32px](https://raw.githubusercontent.com/cxong/cdogs-sdl/ea0651ca5b17538e4bff8694edbc8b43259cee63/build/gcw-zero/cdogs-sdl.png).


The Gnome icons (/usr/share/gnome) seems to use 8, 16, 22, 24, 32, 48, 128, 256, 512. They also come with a scalable flavor which is SVG.

**Comment by cxong** [comment]
I think it'll be good to organise the four base icon types, and create scripts that generate icon sets for each platform. This will make it easier to edit the icons in the future, and to add more icon sizes as needed.

**Comment by hashar** [comment]
Great to see this got addressed, thank you @cxong !
