### ISSUE TITLE
Suspect log

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#523]
![suspicious_log](https://user-images.githubusercontent.com/2904634/29378685-48b47502-82c0-11e7-9141-3d2f23caad00.png)

I was playing the "Sand" campaign, if that helps reproducing.

**Comment by sauer2** [comment]
Another one, slightly different looking:
![2](https://user-images.githubusercontent.com/2904634/29379251-22277374-82c2-11e7-8b67-58ffc041ac61.png)

**Comment by cxong** [comment]
Which platform/OS is this?

**Comment by sauer2** [comment]
Linux based OSes. I upgraded my distribution and tried another one in the last couple of days and it's there as well.

**Comment by cxong** [comment]
Haven't reproduced it yet, but found that colours were broken in linux. That should be fixed, not sure if it also fixes the suspect log.

**Comment by sauer2** [comment]
That seems to do the trick. Thanks.
