### ISSUE TITLE
Cave room generation issues

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#526]
Sometimes the door colors aren't quite right, e.g. I've seen blue doors mixed together with non-key doors.

**Comment by cxong** [comment]
Can you provide an example mission + seed?

**Comment by sauer2** [comment]
@cxong Mission 4 in the campaign I sent you by mail. Seed is set to 0, although the log says its seeding with 30.

**Comment by sauer2** [comment]
Thanks, that fixed it.
