### ISSUE TITLE
Editor bug: Objective count

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#527]
* Create an objective and place some objective objects.
* Now create a second objective and place some objectives for it, too.
* The count of the first objective somehow increases a few numbers, as well.

**Comment by cxong** [comment]
I tried this on new map, classic type, created two collect objectives, increased first objective count to 2, second to 2. First objective is still 2.

Could you please provide steps to reproduce? Maybe example campaign if necessary.

**Comment by sauer2** [comment]
@cxong I probably should have mentioned that this happened in static maps when placing destroy objectives manually, sorry.
