### ISSUE TITLE
Two different versions of rlutil.h

### ISSUE THREAD

**Issue by hashar** [cxong/cdogs-sdl#536]
There are two copies of the lib rlutil in the source code:
```
$ find . |grep rlutil
./doc/license.rlutil.txt
./src/tests/cbehave/rlutil
./src/tests/cbehave/rlutil/README.markdown
./src/tests/cbehave/rlutil/rlutil.h
./src/cdogs/rlutil
./src/cdogs/rlutil/license.txt
./src/cdogs/rlutil/rlutil.h
```

The source repository being https://github.com/tapio/rlutil/

**Comment by cxong** [comment]
rlutil is used by cbehave itself, which is a separate project to c-dogs sdl. Duplication should be fine.
