### ISSUE TITLE
Feature request: Option to remove blood.

### ISSUE THREAD

**Issue by stavrossk** [cxong/cdogs-sdl#544]
Hi, i downloaded CDogs-sdl yesterday and I'm loving it so far. However I don't like blood in the games that I play. Is it possible to add an option in the game to remove blood from the killed enemies on the floor?

Thanks,
Stavros.

**Comment by cxong** [comment]
Thanks, I guess blood should be removed if Graphics / Gore is set to None. WIll add soon.

**Comment by stavrossk** [comment]
@cxong Many thanks for adding the feature!
