### ISSUE TITLE
Unpausing should ignore the keypress

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#548]
The game can be unpaused by pressing fire/switch. But this keypress is then processed as the game unpauses. For example, if you press fire to unpause, the game will continue with the player firing.

There should be either a grace period where the unpausing key is ignored, or that key must be released before its input is used again.

**Comment by sauer2** [comment]
@cxong How about unpausing at key release only?

**Comment by LiquidityC** [comment]
I've got a solution for this. PR incoming
