### ISSUE TITLE
Deploy to itch.io

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#550]
Modify the release script (`.travis.yml`) to deploy new releases to itch.io. There's a page at https://congusbongus.itch.io/cdogs-sdl but it currently only links back to the website.

Itch.io has a client, maybe this means auto-updates can be handled by it? Would be pretty cool.

**Comment by akien-mga** [comment]
itch.io has a nice `butler` client which should let you update binaries with a one-liner. I'm using it to push Godot releases (manually from our build server though, not automated on CI), and it's quite simple.

Docs: https://itch.io/docs/butler/pushing.html

Example usage (for Godot releases, bash script):
```
VERSION=$1
if [ -z "$VERSION" ]; then
   echo "Pass a version string (e.g. '3.0.2-stable') as argument."
fi

butler push Godot_v${VERSION}_x11.64.zip godotengine/godot:linux-64-stable --userversion ${VERSION}
butler push Godot_v${VERSION}_x11.32.zip godotengine/godot:linux-32-stable --userversion ${VERSION}
butler push Godot_v${VERSION}_osx.fat.zip godotengine/godot:osx-fat-stable --userversion ${VERSION}
butler push Godot_v${VERSION}_win64.exe.zip godotengine/godot:windows-64-stable --userversion ${VERSION}
butler push Godot_v${VERSION}_win32.exe.zip godotengine/godot:windows-32-stable --userversion ${VERSION}
```

**Comment by cxong** [comment]
Also: edit the game page to prominently show an itch widget + other download links
can probably remove the gallery it takes a lot of space
