### ISSUE TITLE
(Full-screen) resolution problem.

### ISSUE THREAD

**Issue by Achaean** [cxong/cdogs-sdl#560]
Hi! :-)

I downloaded and run the Linux binary here (at Debian Jessie (oldstable) x64 KDE) and I had a resolution problem.

The only resolution that really worked is the one closest to my screen default (1360X768).
IT ran the game, but the sprites are way to small for me.

Other resolutions, although they ran, the drawing the game partially off-screen (rendering it unplayable).

Windowed mode runs flawlessly.

**Comment by cxong** [comment]
Thanks; I think I will rework the resolution system instead. Currently it tries to look for supported resolutions for your display device, but this is not always reliable.

Instead I'll replace it with a scale setting. Resizing the window will not affect the scale, and full screen will always use the native resolution.
