### ISSUE TITLE
Some keys are not working.

### ISSUE THREAD

**Issue by Achaean** [cxong/cdogs-sdl#561]
Certain (keyboard) keys are not working.
Eg. the ESC. Since I ran it at full-screen mode, I had no way to quit the game (other than switching to another VT and sending a sigkill signal.

Latest release (0.6.7), on Debian Jessie (oldstable) x64 KDE.

**Comment by cxong** [comment]
The game looks for the escape key directly. Can you try an SDL keyboard test program, like this one: https://gist.github.com/DanielGibson/12041b57a540cbbfbaf9 and see if escape is detected correctly?
