### ISSUE TITLE
Split screen is broken - centers on same player twice

### ISSUE THREAD

**Issue by tcpie** [cxong/cdogs-sdl#562]
I just found about this project today and tried to play it with a friend (we really liked the original C-dogs). We wanted to play in coop, but the split screen does not work well. There seems to be some bug which causes both the split screens to focus on the same player, instead of both split screens focusing on two different players...

To reproduce: run any campaign with two players.

I ran into this issue with both the split screen setting set to 'always', as well as when it was set to 'normal'. Please fix this issue, as the game is unplayable in multiplayer at the moment :-(

**Comment by cxong** [comment]
Thanks, I can fix in the next release. In the mean time, can you play with shared screen? You can also use LAN multiplayer with two computers.
