### ISSUE TITLE
Publish flatpak/flathub

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#581]
Flathub: https://github.com/flathub/flathub/wiki/App-Submission

One advantage is this is used by [Athenaeum](https://gitlab.com/librebob/athenaeum#getting-your-game-on-athenaeum), a libre steam clone

**Comment by Rampoina** [comment]
Hello,
I built a flatpak for your game:
https://gitlab.com/Rampoina/com.cxong.cdogs-sdl

there's two issues right now:

- The runtime used has to be 1.6 because the application fails to compile with a few compiler errors (because of -Werror) on later compilers.

- The appstream file included in the game doesn't contain "<oars>" and "<releases>"

I will open the issues for those problems and you can either wait for a new release to include those fixes or create patches and submit it earlier to flathub.

**Comment by Rampoina** [comment]
I confirm that the flatpak is buildable after 43ca6bbf16255bdee9712e0c32e410441d9783f0 on the latest runtime.
I leave it up to you to submit the application to flathub after a stable release including those fixes.
Please let me know if you need any help or if you prefer me to submit it myself.
If you want to submit it earlier let me know.

**Comment by cxong** [comment]
@Rampoina yes please! I haven't submitted to flathub before so if you know how then that would be very helpful

**Comment by Rampoina** [comment]
Hello, I was going to create the PR to flathub but there's one more issue:
The screenshots in the appdata cannot be accessed:

• url-not-found         : <screenshot> failed to connect: SSL handshake failed [https://raw.githubusercontent.com/cxong/cdogs-sdl/master/wiki/images/game_screen.png]
• url-not-found         : <screenshot> failed to connect: SSL handshake failed [https://raw.githubusercontent.com/cxong/cdogs-sdl/master/wiki/images/screenshots/hqx_new.png]
• url-not-found         : <screenshot> failed to connect: SSL handshake failed [https://raw.githubusercontent.com/cxong/cdogs-sdl/master/wiki/images/screenshots/quick_play.png]

**Comment by cxong** [comment]
@Rampoina I've updated the screenshots, please try again

**Comment by Rampoina** [comment]
@cxong 
Unfortunately the screenshots cannot be gifs. The supported formats are as follows [1]:

>  Screenshots should ideally be in the PNG format, but JPEG and WebP images are also fine. Keep in mind though that the images are converted into PNG in any case by the distributor of a software collection. 

[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by Rampoina** [comment]
Just to clarify some things.
1. The flathub maintainers prefer that the flatpaks are owned by the original developers.

    I'm going to submit the flatpak and you could own it if you wish.
    If you decide to own it I would be OK with being set as a maintainer 

2. The flatpaks should only point to stable releases.

    Meaning that if you fix issues like the above, the flatpak that I submit should point to a tagged release, otherwise I have to include a patch (which wouldn't be that much of a problem in this case, but it's always cleaner)

**Comment by cxong** [comment]
Great; I will fix up the screenshots for the next release.

**Comment by librebob** [comment]
Hi @cxong I've modified the manifest for the latest version and submitted to flathub. Please feel free to reach out on the flathub PR if you wish to be a maintainer.

**Comment by cxong** [comment]
Added to https://flathub.org/apps/details/io.github.cxong.cdogs-sdl
