### ISSUE TITLE
Heap corruption on startup

### ISSUE THREAD

**Issue by veikkos** [cxong/cdogs-sdl#608]
**Visual Studio Community 2017
Version 15.9.3**

x86 and x64 build.

Seems to be fully reproducible. Have not been able to figure out the cause. Issue can disappear if adding debug changes to trace the issue, tricky to investigate.

`HEAP CORRUPTION DETECTED: after Normal block (#76601) at 0x00000157B5780010.
CRT detected that the application wrote to memory after end of heap buffer.`

![kuva](https://user-images.githubusercontent.com/24453333/65377624-6e599000-dcb7-11e9-836c-74d184d4db46.png)

![kuva](https://user-images.githubusercontent.com/24453333/65377682-1d966700-dcb8-11e9-9d4d-4ba6781c0170.png)

**Comment by cxong** [comment]
`Character::bot` is lazily instantiated so it's possible it's freeing a garbage value
`CharacterInit` should be setting it to a valid value, so perhaps in some code path the character is not being initialized properly

**Comment by veikkos** [comment]
> `Character::bot` is lazily instantiated so it's possible it's freeing a garbage value
> `CharacterInit` should be setting it to a valid value, so perhaps in some code path the character is not being initialized properly

Debugger has stopped to next line after the real issue. Actual exception happened at `CFREE(c->Hair);`. Issue has been resolved with PR #610.

Closing the issue. Please add a Bug label if you think it's useful for tracking purposes, thanks!
