### ISSUE TITLE
Alt/Option + Enter to toggle fullscreen

### ISSUE THREAD

**Issue by veikkos** [cxong/cdogs-sdl#612]
Alt + Enter (or Option + Enter on OSX) is a common key combination to toggle fullscreen. It would be nice to have it in the game.

**Comment by cxong** [comment]
Control-Command-F for macOS https://support.apple.com/en-us/HT201236

**Comment by cxong** [comment]
Full screen option not needed for macOS since you can use the system shortcut (or the green maximise window button)
