### ISSUE TITLE
Grave Intent, level 4 might be impossible

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#619]
How to reproduce:

* Use CDogs SDL 0.7.0
* Start the Grave Intent campaign
* Set the seed to 0
* Play level 4

In this level, the yellow key will spawn exactly on one of the yellow doors and is impossible to reach. But you need to open the yellow door to complete this level. Thus it is impossible.

The level might be possible for other seeds, however.

**Comment by Wuzzy2** [comment]
There's another level that is unsolvable:

Distress from Scientific Outpost, level 8
Seed = 2147483638

In this level you spawn in a locked room with a yellow door but no yellow key.

**Comment by cxong** [comment]
There are no locked doors for me in grave intent; I think seed isn't portable so I'd need to know your OS - is it linux?

**Comment by Wuzzy2** [comment]
Yes, it is GNU/Linux.

Also, I am on commit 9a9216fdf181e809ef66e68c0d1fcf730af82930.

It's very weird why you have no locked doors. Are you sure you played level 4?

**Comment by Wuzzy2** [comment]
I just did a full git re-clone and re-build and deleted my config, then tried again. The bug still occurs exactly as before.

**Comment by cxong** [comment]
I've been able to recreate a related bug I think, where you start the game in a locked room - in a different campaign however.
