### ISSUE TITLE
Bullet holes in doors behave incorrectly

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#623]
If you shoot bullets into a closed sliding door so that the door gets bullet holes, then walk into the door to force it to slide down, the bullet holes don't disappear. Instead, they are now rendered on the floor. Which looks odd.

Version 0.7.0

**Comment by cxong** [comment]
![bulletmarks](https://user-images.githubusercontent.com/1083215/70230330-33420580-17ac-11ea-9064-7cc8a2ed4c89.gif)
