### ISSUE TITLE
Red doors aren't red sometimes

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#626]
Version: 0.7.0

While playing this game for a while in v0.7.0, I noticed that in a couple of levels, the red doors aren't actually red. They are gray. But they behave like a normal locked red door. It's just they aren't red for some reason. I know these doors are red in function because they are locked when I walk into them without a red key and they are passable when I got the red key.

This only happens sometimes. And I have no idea what exactly I must do to trigger it.

Unreliable (!) steps to reproduce:

* Play any level where you know that it contains red doors
* Explore the level and check if the doors are actually red

This may or may not trigger the bug.

**Comment by cxong** [comment]
Can you give an example of map and mission number where you've seen this?

**Comment by Wuzzy2** [comment]
I will post it when I see this bug again.

**Comment by cxong** [comment]
I can repro this on AI Insurgency mission 5
