### ISSUE TITLE
Ammo loadout: GUI improvements

### ISSUE THREAD

**Issue by Wuzzy2** [cxong/cdogs-sdl#630]
This issue is a list of small suggestions for the ammo loadout menu, GUI related.

I find it annoying that when the next mission starts and I am in the ammo loadout menu, I *always* must open 2 ammo slots (gun and grenade) first to see if I got any interesting new weapons. Each mission might give new weapons, so I must do this every time. If I do not open any ammo slot and just start playing blindly, I might be missing out on new guns. Sometimes the correct weapon selection can be critical to success.

So I have the following suggestions:

1. Display the weapon icons of all available weapons somewhere on the screen, visible at all times as long you're in the ammo loadout menu (display it somewhere where it doesn't collide with any other graphics or text)
2. When a weapon slot is hovered, display the icon of that weapon (just like in the weapons list when you opened a weapon slot)

Number 1 will mean that the player can see all available weapons at a single glance and can decide faster whether it's needed to change the weapons or not. The player will no longer be forced to actively open any ammo slot just to know which weapons are available.

Number 2 is just for consistency's sake. I posted it because it's kinda related.

**Comment by cxong** [comment]
![equip menu](https://user-images.githubusercontent.com/1083215/102985208-e8d02a00-4562-11eb-9369-c4258e829bf4.gif)
