### ISSUE TITLE
Background using uninitialized memory on startup

### ISSUE THREAD

**Issue by swills** [cxong/cdogs-sdl#657]
It seems like there may be some RAM used uninitialized on startup [here's what I see](https://i.imgur.com/NqcGSOd.png). Is this known? (This is 0.9.0 but the previous version did this too, just decided to report it now)

**Comment by cxong** [comment]
Thanks for raising; can you please provide more details, like
- OS
- Sequence of actions to reproduce
- Graphics settings (e.g. windowed/fullscreen, resolution)

**Comment by swills** [comment]
I'm using FreeBSD. (I'm maintaining the FreeBSD port which is used to build packages.) The sequence of actions is just to start the game. I'm using full screen at 1920x1080 resolution.

**Comment by chack05** [comment]
I have this, too, on Ubuntu Linux 20 LTS. The debugging window says

    20201021-224044 ERROR [GFX  ] [window_context.c:74] WindowContextInitTextures(): cannot set renderer logical size: Invalid renderer

**Comment by chack05** [comment]
It also happens in the editor, right from the beginning.

**Comment by swills** [comment]
Seems fixed in 0.10.1
