### ISSUE TITLE
Dual wielding

### ISSUE THREAD

**Issue by chack05** [cxong/cdogs-sdl#661]
Since you have that long, long list of features you want to implement, I thought, why not add another ;)

**Dual wielding**

Exactly what it says, a character can carry two of some kinds of weapons.

**How picking up/dropping could work**

* Picking up a second weapon makes the HUD show a **2x**.
* Dropping a dual wielded gun in favor of another pickup requires the game to remember the count.
* Should the player be allowed to go back to one gun?

**Weapon properties that are probably required**

* dual_wield as boolean (or as number, in case you'd want to basically implement a Doom Russian Overkill kind of campaign)
* duration between firing gun 1 and 2 (think pistol vs shotgun requirements)
* duration after the complete firing cycle of gun 1 and 2 (think of increased reload times for single shot weapons and repeating guns)
* angle between both guns
* accuracy penalty
* different timing for reloading sounds
* ammo use factor, if ammunition is still a thing
* ?

**Comment by cxong** [comment]
https://user-images.githubusercontent.com/1083215/116805200-1f98fb00-ab68-11eb-9a9d-50428c1e27f9.mp4
