### ISSUE TITLE
Trailer and hitscan issues

### ISSUE THREAD

**Issue by chack05** [cxong/cdogs-sdl#662]
These might be feature requests, bug reports, impossible to implement or simply me being being not smart enough to figure out the settings correctly...

* Making the mining laser from Harmful Crysalis bounce of the wall doesn't seem to work.
* SeekFactor doesn't seem to work at all. I know, weird idea, but think of lightning guns, magic, etc.
    * Also, the browny gun property Erratic might make sense here.
* Since trails are not documented yet, is it possible to set the length of the trail?
* Needler -> trails: Yay or nay?

**Comment by cxong** [comment]
SeekFactor is a bit odd - the lower the number the quicker the bullet seeks. Compare the heatseeker (20) which seeks better than the swarmer (30).

**Comment by cxong** [comment]
Trail (I assume you mean the bullet trail for the pistol) stretches from the bullet's current position to its last, so the length is determined by bullet speed. The pistol bullet travels instantaneously which leads to a long trail. You can also modify the trail length by increasing its particle Range (lifespan in game ticks). The rockets use animated smoke trails to achieve this effect.

**Comment by chack05** [comment]
@cxong I tried to change the SeekFactor to 1, 0.0001 and -1 but it still doesn't seem to work for hitscan weapons.

If I understood you correctly, the length of the animation decides the lifespan of a particle?

**Comment by cxong** [comment]
SeekFactor won't work with hitscan weapons - the code isn't designed for fast bullets, it gradually steers the bullet towards the closest target. There are also hard coded limits on how much it will steer. It was only really designed with homing missiles in mind, and not really well tbh. Some more thought needs to be put into it to support hitscan seeking - or if we need two separate systems.

**Comment by cxong** [comment]
![wallbounce laser](https://user-images.githubusercontent.com/1083215/97165960-9380d200-17d8-11eb-9ff5-54e4ae4ca47d.gif)
Added wallbounce hitscan

**Comment by chack05** [comment]
@cxong Pretty cool. Perhaps I get round to create a dogfight map. Do you include more dogfight maps at this point?

**Comment by cxong** [comment]
Sure, why not!
