### ISSUE TITLE
Blood colour per character

### ISSUE THREAD

**Issue by chack05** [cxong/cdogs-sdl#663]
As a feature request: Blood colour that overwrites the colour specified by the character class.

**Comment by cxong** [comment]
I'm not sure about this - I feel that blood colour should be tied closely with the character class, which also determines things like character sounds (death/awake sound) and compatible hairs/hats.

If this is for special characters for campaigns (e.g. boss creatures), we can support this by creating a new character class. Otherwise it seems overkill for players to be able to customise their blood colours.

**Comment by chack05** [comment]
>If this is for special characters for campaigns (e.g. boss creatures), we can support this by creating a new character class.

I was contemplating creating a map with Sin City/Madness Combat look-and-feel, so loading an additional character_classes.json file would be great if it's not too much work. Not sure how far you want to go in terms of moddability.

**Comment by cxong** [comment]
This might work already - try adding a custom `character_classes.json` file in the campaign
It is not used currently in any existing campaigns

**Comment by chack05** [comment]
@cxong I tried it, but somehow it crashes the game. Sent the campaign to your geemail account for further analysis...

**Comment by cxong** [comment]
I cannot reproduce by copying a character_classes.json file into a custom campaign. I haven't received your campaign - was it sent or blocked?

**Comment by chack05** [comment]
@cxong Not that I'd know about. I sent it with my old "sauer2" account but didn't receive any kind of warning.

**Comment by cxong** [comment]
Custom character classes should work - I added an example in the graveintent mission

**Comment by chack05** [comment]
@cxong It works. Must have been another error in my test campaign. But the blood shows rather dark. Is this as intended?

**Comment by cxong** [comment]
Yes - blood can only be so bright because the base image has limited brightness. This is to avoid the visuals from becoming too messy.
One thing we could do is similar to the brass shells - darken them over time, so that they start bright.
