### ISSUE TITLE
Trail drawn to window origin

### ISSUE THREAD

**Issue by ghost** [cxong/cdogs-sdl#664]
![trail_bug](https://user-images.githubusercontent.com/12168893/95374336-7e520b00-08de-11eb-83e3-434994bc9f90.png)
Apparently when a player shoots near the left end of the loaded map, the bullet trail is drawn from the weapon to 0, 0.

**Comment by cxong** [comment]
![Image](https://github.com/cxong/cdogs-sdl/assets/1083215/cd64eae8-9e9a-4b91-b206-e04ca305c29f)

cannot reproduce
