### ISSUE TITLE
Game crashes when enemy throws purple grenades and static explosive objetcs get destroyed.

### ISSUE THREAD

**Issue by STRRRRR** [cxong/cdogs-sdl#684]
In either of those 2 cases the game crashes.

Version: C-Dogs.SDL-0.10.0-win32.exe downloaded from https://github.com/cxong/cdogs-sdl/releases
I don't know if I'm soppused to install anything else.

Windows version: 7 64 bits.

**Comment by cxong** [comment]
Thanks for raising! I believe this is the same issue as #686

**Comment by PavanLuca** [comment]
It crashes on my laptop, too. I saw it in few minutes of play, I wanted to try all modes and when I entered the red dungeon I collected a grenade and when I threw it the game just crashed.

Flatpak, version 1.4.1, in Zorin OS Core

**Comment by cxong** [comment]
^ please open a new issue, this is a super old bug
