### ISSUE TITLE
Game crashes when loading any campaign from Missionpack.zip

### ISSUE THREAD

**Issue by viki-t-s** [cxong/cdogs-sdl#692]
**Action:** 
Trying to play one of the missions .cpn files.

**Actual:** 
The game simply crashes without any error when trying to open a Campaign .cpn file

**Expected:**
The campaign loads and plays.

**Steps to reproduce:**
Try to open any .cpn mission
Start -> Campaign -> Custom\ ->Any .cpn mission (I chose Boom (1))

**Additional Information:**
**Software Version** C-Dogs.SDL-0.10.1
**Game path** C:\Users\xxxxx\Desktop\C-Dogs.SDL-0.10.1-win32
**CPN files path** C:\Users\xxxxx\Desktop\C-Dogs.SDL-0.10.1-win32\missions\custom
**Operating system** Windows 10 64 bit Version 1909 (OS Build 18363.1198)

**Comment by viki-t-s** [comment]
Same crash happens when trying to open a DF file as well

**Comment by cxong** [comment]
Thanks for raising! This has been fixed and will go out with the next release

**Comment by viki-t-s** [comment]
Thank you!

> Thanks for raising! This has been fixed and will go out with the next release
