### ISSUE TITLE
Adhere to XDG Base Directory Specification 

### ISSUE THREAD

**Issue by Mailaender** [cxong/cdogs-sdl#754]
The hardcoded

https://github.com/cxong/cdogs-sdl/blob/d99a1999a19ae78ee28d9cfdea51c996a461b092/CMakeLists.txt#L156

breaks https://github.com/flathub/io.github.cxong.cdogs-sdl/issues/1.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by cxong** [comment]
What's the tl;dr of this? XDG_CONFIG_HOME defaults to `.config` so why doesn't this work? Does the spec say the config files (this game uses 3 or 4 different files) should all be in `.config` and not a subfolder?

**Comment by Mailaender** [comment]
Don't hardcode at build time. Use the environment variable at runtime. Even though in the default configuration, the result is the same. This is useful in this case for backwards compatibility.

**Comment by cxong** [comment]
Pushed a PR but I don't have a linux to test it, can you help verify that this resolves the issue?

**Comment by Mailaender** [comment]
I still get

> ERROR [MAIN ] [player_template.c:110] PlayerTemplatesLoad(): loading player templates 'players.cnf'

but saving settings works.
