### ISSUE TITLE
Game freezes when adjusting audio in C-Dogs SDL v. 1.4.0

### ISSUE THREAD

**Issue by RenniStuffmin** [cxong/cdogs-sdl#756]
Hi! So I had just downloaded and installed C-Dogs SDL version 1.4.0 for my Windows 10 machine, and I've run into a problem.

Whenever I try to adjust the volume levels, whether it be that of the music or sound, the game would freeze completely (aside from the music), forcing me to close the game.

I've also noticed that the command prompt window that opens alongside the game has the line "Audio not what we want." repeated a few times; perhaps that has something to do with my problem?

I feel like this is an issue on my end, but is there any way I can fix this? Thanks in advance!

OS: Windows 10
Game Version: 1.4.0

Steps to Reproduce:
1.) Start game and got to Options... -> Sound...
2.) Adjust either Music or Sound Volume

**Comment by cxong** [comment]
Cause of bug is https://github.com/libsdl-org/SDL/issues/4604

**Comment by RenniStuffmin** [comment]
> Cause of bug is [libsdl-org/SDL#4604](https://github.com/libsdl-org/SDL/issues/4604)

A'ight, cool! Thanks!
