### ISSUE TITLE
Hide quickplay

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#762]
Quickplay was added as a quick and easy way to jump in and play the game with a random level, however now that we have lots of cool built-in campaigns, its quality is very lacking in comparison, and new players often jump into this mode and get a false impression of what C-Dogs SDL is really capable of.

Therefore hide this menu for now. We can add it back in if and when we extend it so that it creates content of comparable quality.

**Comment by PavanLuca** [comment]
I like Quick Play because it's really quick, few minutes each and it's done, great mode for who has short time for a break, please don't remove it. Sometimes I prefer doing short fights rather than long campaigns so this mode is perfect.
