### ISSUE TITLE
Misplaced stuff

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#765]
Happens frequently.
![Schermata da 2023-05-19 04-55-19](https://github.com/cxong/cdogs-sdl/assets/123581658/698b20c7-c185-48b1-98c7-f400e0ace904)
![Schermata da 2023-05-21 12-37-23](https://github.com/cxong/cdogs-sdl/assets/123581658/2b750991-3dc0-4892-aa6c-b83b53a5f641)
![Schermata da 2023-05-25 18-13-34](https://github.com/cxong/cdogs-sdl/assets/123581658/78cdbb2d-1f46-46c9-9d74-0301be47a61e)

**Comment by cxong** [comment]
I believe these are all from the quick play mode which we've since removed; will close for now
