### ISSUE TITLE
Impossible

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#776]
How to win 🔍️🧐️😏️🔭️🔎️?
![Schermata da 2023-05-30 23-31-04](https://github.com/cxong/cdogs-sdl/assets/123581658/dfa4829f-47dc-45bd-be84-24c38aacbd81)
![Schermata da 2023-06-03 10-59-59](https://github.com/cxong/cdogs-sdl/assets/123581658/b4cee5ea-1360-4380-998f-d1dd22c0bdc7)
![Schermata da 2023-06-03 11-00-05](https://github.com/cxong/cdogs-sdl/assets/123581658/b62f17c7-b6a5-4b20-82e5-84ba98cfd37a)
![Schermata da 2023-06-04 17-43-37](https://github.com/cxong/cdogs-sdl/assets/123581658/10ad4151-dcb7-4738-904a-0e5ca392e3ed)
![Schermata da 2023-07-02 00-15-21](https://github.com/cxong/cdogs-sdl/assets/123581658/af34cf57-9b0a-4fec-aebb-443526b0cdc5)
![Schermata da 2023-07-02 00-15-21](https://github.com/cxong/cdogs-sdl/assets/123581658/5c08faeb-1a63-41ed-9bc4-97d161dbbd1c)
![Schermata da 2023-07-14 14-32-55](https://github.com/cxong/cdogs-sdl/assets/123581658/2e9f569d-4f4b-4218-8db1-95925f483dea)
Alright, I stop it here, I think I added enough evidence so far, don't you think 🤣?

**Comment by cxong** [comment]
I think this is all quick play, closing
