### ISSUE TITLE
Very big HUD map

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#782]
Is it related to scaling factor value? In any case, the HUD map should never be cut off from the screen.
![Schermata da 2023-06-01 15-07-33](https://github.com/cxong/cdogs-sdl/assets/123581658/6b7a91e2-f6bf-41de-baf7-60648f5efb40)

**Comment by cxong** [comment]
![Image](https://github.com/cxong/cdogs-sdl/assets/1083215/cf6bfc44-59db-42b0-9ccd-07b26520aa59)

**Comment by PavanLuca** [comment]
So the problem was that the map feature wasn't being scaled according to the chosen scaling size from the settings?
