### ISSUE TITLE
Heavy weapons handling

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#783]
Adapt right arm to hold heavy weapons with 2 hands, running downward with guns like Pulse Rifle and Shotgun you can see 3 hands ✋✋✋😲.

**Comment by cxong** [comment]
Please attach a screenshot, at least I don't see a problem with this weapon:
<img width="137" alt="image" src="https://github.com/cxong/cdogs-sdl/assets/1083215/7dd70573-ae67-4142-9e1f-2c5e965bcd7a">
Left hand under barrel, right hand on the grip

**Comment by PavanLuca** [comment]
Here you can see his left arm not holding the weapon under the barrel.
![Schermata da 2024-03-05 14-45-43](https://github.com/cxong/cdogs-sdl/assets/123581658/71889dbe-579e-4737-a1fb-4294e5845bbb)
![Schermata da 2024-03-05 14-46-10](https://github.com/cxong/cdogs-sdl/assets/123581658/bad21449-5ce6-44fa-8f33-65e60c7ed5b7)
The hand is drawn on the weapon as it should but the character animation (both standing and running) shows the same arm as if he's holding nothing.

**Comment by cxong** [comment]
![gun](https://github.com/cxong/cdogs-sdl/assets/1083215/2e48e789-586e-42de-859c-6fe19e9f7451)
it's hard to see with a character with similar skin and arm colours, so here's a demo with different body colours
you can't see three hands; the arm does look weird in the west facing direction but I don't think it's a big deal since there are so few pixels

**Comment by PavanLuca** [comment]
Oh, ok, seems that it's only on my version then, on mine the left arm is
still visible as part of the running animation despite, as I said, when I'm
holding a weapon with both hands it should be holding the weapon barrel. On
your one I see that the left arm is invisible 😄. I wonder why the flat
owners didn't update their version following your one, this behavior on
snaps and flats is “a bit” annoying 😮‍💨.

Il giorno dom 10 mar 2024 alle ore 07:23 Cong ***@***.***> ha
scritto:

**Comment by PavanLuca** [comment]
Oh, ok, seems that it's only on my version then, on mine the left arm is
still visible as part of the running animation despite, as I said, when I'm
holding a weapon with both hands it should be holding the weapon barrel. On
your one I see that the left arm is invisible 😄. I wonder why the flat
owners didn't update their version following your one, this behavior on
snaps and flats is “a bit” annoying 😮‍💨.
