### ISSUE TITLE
Hair/hat saving fails

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#786]
After saving the hair/hat chosen is saved for the current game session, it isn't loaded the next time that the game is started again.

**Comment by cxong** [comment]
This is intentional; if a campaign has special player templates, those will be used by default - you will still be able to choose saved player templates from the load player template menu

**Comment by PavanLuca** [comment]
I know, the problem is that the hair/hat that I saved on my own template is never saved correctly so when I close the game and reopen it I always find my character without hair/hat, this is too annoying, I can't always restore them each time. I know that some campaigns replace the template but they don't delete my hair/hat, I can use custom templates that the campaign proposes but this doesn't mean that the game has to forget my own template hair/hat.
