### ISSUE TITLE
Dangers awareness for AI

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#798]
Enemies, allies and neutral or harmless beings always suicide or get hurt by running in the middle of shootouts, fire, poison or explosions. Add a danger detection system to make them react accordingly, for example when hearing shots or see a gunned, dangerous or scary being they run away and when seeing fire they stop running to avoid stepping on it and simply run on the opposite direction, that's anyway a wise behavior good for almost any situation.

**Comment by cxong** [comment]
Dup of #24
