### ISSUE TITLE
Character health loss amount text

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#808]
When the character is hurt it shows the whole level damage taken so far instead of only the current hits damage.
![Schermata da 2023-07-25 16-11-30](https://github.com/cxong/cdogs-sdl/assets/123581658/27f4a9be-6816-4030-8f70-69ef2395164d)

**Comment by cxong** [comment]
`Actor` contains a field `accumulatedDamage` which stores this amount; it seems this never gets reset. It should be reset after a period of no change, say 1 second (Game.FPS ticks)

**Comment by Hrvt2** [comment]
I would like to try and solve this issue

**Comment by cxong** [comment]
ok
