### ISSUE TITLE
Friendly fire on Distress call from scientific outpost

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#813]
On Distress call from scientific outpost only level 15 should have friendly fire enabled as enemies are together with allies and as challenge the player must kill only enemies and the enemy commander but any other level it should have it disabled since on these levels soldiers are all allies.

**Comment by cxong** [comment]
we don't want to change any of the classic levels (made by Ronny Wester), they should stay the same as original C-Dogs
