### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#818]
There are some typos scattered throughout the game, you can use the [LanguageTool](https://languagetool.org/?force_language=1) website for help in correcting them, such as missing spaces after …, incomplete words and more, it shows typos in a glance making corrections easier.

Incomplete word
![Schermata da 2023-07-09 15-57-34](https://github.com/cxong/cdogs-sdl/assets/123581658/1e1632ca-0b6f-4f33-a148-a0cade70d713)

Intelligence are 👉 Intelligence is
particulary 👉 particularly
are giving us 👉 is giving us
![Schermata da 2023-07-09 16-33-49](https://github.com/cxong/cdogs-sdl/assets/123581658/42c811fe-9954-4884-9ef8-020d399c535f)

piece 👉 peace
![Schermata da 2023-07-09 17-19-56](https://github.com/cxong/cdogs-sdl/assets/123581658/86b82ad1-341d-48e6-8f61-be20111a5e04)

you can some 👉 you can deal some
![Schermata da 2023-07-10 14-10-07](https://github.com/cxong/cdogs-sdl/assets/123581658/df272e55-ac99-4c36-8047-d1919ae3a3bf)

Space after …
![Schermata da 2023-07-10 14-34-00](https://github.com/cxong/cdogs-sdl/assets/123581658/5f06b227-d21c-4edd-8075-39378143cee9)

If you tell me an example of the texts location I can use it to find others and correct them, I'll practice with pull requests 😁.

**Comment by cxong** [comment]
you can use github code search to find these texts
