### ISSUE TITLE
Wrong blood animation

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#827]
Game loads wrong blood animation when killing bug monsters on Harmful Crysalis (Chrysalis by the way).
![Schermata da 2023-10-09 17-29-37](https://github.com/cxong/cdogs-sdl/assets/123581658/7357ba00-fe8b-4496-922b-acc567587d5b)
![Schermata da 2023-10-09 17-29-39](https://github.com/cxong/cdogs-sdl/assets/123581658/3e08074b-5632-4e6d-aae9-9f65dd416544)

**Comment by cxong** [comment]
I haven't checked this out yet, but characters can have different blood colours. Are you sure this is not expected? Which characters have the wrong blood colour - and what should they be instead?

**Comment by PavanLuca** [comment]
I meant the bug monster, not the player's character 😉. As you can see, I screenshotted right when I killed a bug monster and you can see red blood animation when instead they have blue blood. Blue blood is loaded once the red blood animation ends though, weird 🤪😆.

**Comment by cxong** [comment]
This is not a bug - the monsters appear red tinted due to the mining laser's "flamed" effect
if you shoot them with other weapons, their blood colour will show correctly
