### ISSUE TITLE
Re-evaluate OARS categorization

### ISSUE THREAD

**Issue by reinerh** [cxong/cdogs-sdl#849]
The AppData file currently adds an empty OARS rating (added in #617):
https://github.com/cxong/cdogs-sdl/blob/648dce2462afe59bbf42a2411067bb681d5554d9/build/linux/io.github.cxong.cdogs-sdl.appdata.xml#L6

This should probably get updated, as the game contains at least some violence.
There is a generator available at: https://hughsie.github.io/oars/generate.html

**Comment by cxong** [comment]
```
  <content_rating type="oars-1.0">
    <content_attribute id="violence-cartoon">intense</content_attribute>
    <content_attribute id="violence-fantasy">intense</content_attribute>
    <content_attribute id="violence-bloodshed">mild</content_attribute>
    <content_attribute id="language-humor">mild</content_attribute>
    <content_attribute id="social-chat">mild</content_attribute>
  </content_rating>

```
