### ISSUE TITLE
Manual Save or Quicksave

### ISSUE THREAD

**Issue by rambo919** [cxong/cdogs-sdl#862]
One thing that always annoyed me about DOS games was pressing Esc in a hurry could accidentally quit the game but that questionable command choice aside....

What is the chance of implementing ingame saving? On small maps no saving is fine but for large complicated maps this is definitely needed by me at least. ADHD is not your friend with games that don't allow you to save when you need to.

**Comment by cxong** [comment]
There is very little chance this will be implemented; saving games is a complex procedure and missions are usually doable within a few minutes, so this is very little gain for high cost.

The latest release removed the double-escape-quit feature and replace it with a pause menu. See https://cxong.github.io/cdogs-sdl/release/2024/04/12/c-dogs-2.1.0.html
