### ISSUE TITLE
Cdogs => Failed to load wolf sound 58: -1

### ISSUE THREAD

**Issue by Kelvfimer** [cxong/cdogs-sdl#865]
Getting 33mmap_wolf.c:918[0m] [22;36mLoadSoundData()[0m: [22;31mFailed to load wolf sound 58: -1 when loading Wolfenstein 2D (episode 1) (wold3d) 

Platform
---------------
odroid n2+ 4GB, linux 4.9, SDL2 2.28.5 
latest commit https://github.com/cxong/cdogs-sdl/commit/b61b47dcbe628bacb37f61974c1d1e36fbc7c867

Repro
---------
Start the game 
Select campaign
Select Wolfenstein 2D (episode 1) (wold3d) 
Screen is stuck on loading game

Logs
----------------------
[cdogs.log](https://github.com/user-attachments/files/17926495/cdogs.log)

Expected behaviour 
--------------------
to load the campaign

**Comment by cxong** [comment]
The game should ignore sounds it cannot load - perhaps it is getting stuck elsewhere

**Comment by Kelvfimer** [comment]
@cxong  thx for taking a look into it :)
