### ISSUE TITLE
Create deb package

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#89]
Also:
- Create separate cdogs-sdl and cdogs-sdl-data packages
- Submit to debian
##

**Comment by HEXcube** [comment]
Playdeb has already produced _cdogs-sdl_ deb packages and is available for current **Ubuntu** releases.  See the packaging data for _cdogs-sdl_ at [Playdeb's github repo](https://github.com/ckorn/PlayDeb/tree/trusty/cdogs-sdl).  I've installed and tested the package on my *Ubuntu 14.04LTS* and it runs fine.
This game really deserves to be on the **Debian** repo. You guys should submit the package for inclusion in Debian. Once it's made its way into Debian, it'll automatically be syncd into all derivative distros (including Ubuntu! ).

**Comment by cxong** [comment]
Thanks for the info @HEXcube ! Looks like some changes to CMakeLists.txt are required (https://github.com/ckorn/PlayDeb/blob/trusty/cdogs-sdl/patches/install.patch) but I'm not familiar with debian packaging, maybe @carstene1ns can help here?

As for inclusion into Debian, yes this has been an important goal for a long time, unfortunately the graphics are freeware, and not under a ["debian free"](https://www.debian.org/intro/free) license, so they probably will reject it as-is. To comply we'll need to replace all the non-free assets with free replacements. That will take time as not only is it hard to produce perfect replacements (with the right dimensions and so on), many code changes are also needed since the graphics and rendering code are tightly coupled. Those tasks are tracked here: #336

**Comment by HEXcube** [comment]
The package can still make it into Debian repos even if some components (game graphics in this case) are not ["debian free"](https://www.debian.org/intro/free). According to [Debian Free Software Guidelines](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#dfsg)  (DFSG), the proprietary components can go into *non-free* repo, while the free parts will go into *contrib* repo. I think you should try submitting *cdogs-sdl* into Debian right now. Later when #336 is completed and all non-free parts are replaced with free ones, Debian will change the package to the fully free *main* section.

**Comment by cxong** [comment]
@HEXcube that sounds like a good approach and would be useful even after the non-free content is replaced - the cdogs-sdl-data package can then contain only the original, non-free content for those who prefer them. It's not something I can work on right now, I'm unfamiliar with building debs and the debian submission process (do they have special requirements for submitted packages?) but I'll include these in this issue: creation of separate cdogs-sdl.deb and cdogs-sdl-data.deb plus submission to debian.

**Comment by HEXcube** [comment]
When all non-free content is replaced by free ones, I don't think there's any real need to keep the non-free ones. Debian does have some non-free packages in their repos, but afaik they offer some advantages over the currently available free ones. Such packages are mostly firmwares, drivers and other "can't live without" proprietary stuff. I don't know if Debian will keep a **cdogs-sdl-data-nonfree** package if a better open replacement is already available. Also, users tend to prefer open replacements if there's no real gain in using their proprietary equivalents. Anyway, @cxong let's not worry about that too much for now. Let's just try to get **cdogs-sdl** and **cdogs-sdl-data** in it's current state into Debian's *contrib* and *nonfree* repos.

**Comment by hashar** [comment]
If I got it right, one of the potential annoyance was that some sprites/graphics were not free. It seems to have been tracked by #336 which is apparently closed.  So I guess it is 100% open source / libre now? :)

**Comment by cxong** [comment]
Yes.

I don't know how to get a package into debian though, seems like a debian maintainer needs to get involved? Help is welcome

**Comment by hashar** [comment]
I gave it a try tonight and went with some source code patches: #531 #532 #533

I have targeted Debian stretch for now, the very rough packaging is at:

https://github.com/hashar/cdogs-sdl/tree/debian

The patches from the above pull requests are pilled in a different branch https://github.com/hashar/cdogs-sdl/tree/patch-queue/debian . I then use `gbp pq` to regenerate `debian/patches` in the debian branch.

I got it installed and managed to play a little bit :]

Uploading to debian.org would surely be the end goal, but that is really the very last step. We can look at polishing a package and I am willing to help. Then on top of my head we want:

* clarify the copyright status and license of all assets. Debian is VERY strict about that (for good reason: it is a 100% free - as in speach - distribution).
* figure out a name for the package. I went with `cdogs-sdl` after the Debian repo, but maybe `c-dogs` would be more appropriate
* fill an _Intent To Package_ https://wiki.debian.org/ITP , I guess I will do it
* find a mentor to help. That is a Debian Developer that would help review the packaging and give guidance to polish it up.
* get people to try out the package and fix up bugs :]
* then I guess we can bother looking at how to get it uploaded

**Comment by hashar** [comment]
Additional note: the debian packaging work might be done on Debian infrastructure. They have several teams per area of interest/technology, and they will then be able to assist with the maintenance.

For example https://wiki.debian.org/Games/Development

**Comment by hashar** [comment]
#531 #532 #533 have all be merged (thank you!)

I am digging in the files to write a proper `debian/copyright`, it is going to take a while though.

Seems some sounds have been scrapped from movies or games, that might well be an issue :-( But I am not a lawyer. I will send more pull requests to tweak the copyright notices here and there.

**Comment by cxong** [comment]
Thanks; to my knowledge the scraped sounds have all been removed, all the current ones can be accounted for but it may not be obvious. Let me know if you're unsure about any specific assets.

Most assets have a text file with a similar file name that track where they were obtained and their license.
Some graphics are authored by Ronny Wester for the original C-Dogs game; there's a list at https://github.com/cxong/cdogs-sdl/blob/master/graphics/originals.txt, all are under CC-BY 3.0
If not specified, then the author should be myself, license CC0.

For the custom missions, the ones authored by sauer2 should all be CC0.

**Comment by cxong** [comment]
Should probably move towards package managers like flatpak/snap
